// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBwu-wDMebGi4SBRiyCW28njTI-PQHM4g',
    appId: '1:52817044380:web:702fddcc7f4710f7bdde59',
    messagingSenderId: '52817044380',
    projectId: 'freshclips-d3f2b',
    authDomain: 'freshclips-d3f2b.firebaseapp.com',
    storageBucket: 'freshclips-d3f2b.appspot.com',
    measurementId: 'G-6JPL01CRH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiFt-EmF19gHjxxvzFZNkdztWACP3R1t4',
    appId: '1:52817044380:android:a00cbf8c90794d81bdde59',
    messagingSenderId: '52817044380',
    projectId: 'freshclips-d3f2b',
    storageBucket: 'freshclips-d3f2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2FT3caFg-Shdpm2pPHA2cBNyEsjkKao',
    appId: '1:52817044380:ios:3b8ef06f8045b104bdde59',
    messagingSenderId: '52817044380',
    projectId: 'freshclips-d3f2b',
    storageBucket: 'freshclips-d3f2b.appspot.com',
    iosBundleId: 'com.example.freshclipsCapstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2FT3caFg-Shdpm2pPHA2cBNyEsjkKao',
    appId: '1:52817044380:ios:3b8ef06f8045b104bdde59',
    messagingSenderId: '52817044380',
    projectId: 'freshclips-d3f2b',
    storageBucket: 'freshclips-d3f2b.appspot.com',
    iosBundleId: 'com.example.freshclipsCapstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBwu-wDMebGi4SBRiyCW28njTI-PQHM4g',
    appId: '1:52817044380:web:009d478d00b2a579bdde59',
    messagingSenderId: '52817044380',
    projectId: 'freshclips-d3f2b',
    authDomain: 'freshclips-d3f2b.firebaseapp.com',
    storageBucket: 'freshclips-d3f2b.appspot.com',
    measurementId: 'G-LHZ93272DL',
  );

}